# Generated by Django 4.2.2 on 2023-08-21 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="brand",
        ),
    ]
