# Generated by Django 4.2.2 on 2023-06-26 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
