# Generated by Django 4.2.2 on 2023-08-21 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_remove_car_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="accessories",
        ),
    ]
