# Generated by Django 4.2.2 on 2023-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0004_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Acessory",
                "verbose_name_plural": "Acessories",
            },
        ),
    ]
