# Generated by Django 4.2.2 on 2023-06-28 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0005_acessory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Acessory",
        ),
    ]
