# Generated by Django 4.2.2 on 2023-06-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0008_color_alter_car_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
