# Generated by Django 4.2.2 on 2023-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0009_alter_car_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="accessories",
            field=models.ManyToManyField(related_name="cars", to="garage.accessory"),
        ),
    ]
